trigger:
 - develop
 - release/*
 - master

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: Version
- group: Build-Defaults
- name: appName
  value: 'app-assessments'
- name: package
  value: 'WebAPI'
- name: projectPath
  value: 'tickit-app/'

name: $(Major).$(Minor).$(Patch).$(Rev:r)

resources: 
  repositories: 
  - repository: Templates
    name: 'devops-templates'
    type: git 
    ref: 'feature/assessment'

stages:
- template: stages/deploy-ruby-app-service-stages.yml@Templates
  parameters:
      buildConfiguration: $(BuildConfiguration)
      azureSubscription: $(AzureSubscription)
      projectPath: $(projectPath)
      appName: $(appName)
      package: $(package)

